spring:
  config:
    import: classpath:application-secret.yml

  application:
    name: coin-auto-trading

  profiles:
    active: secret

  #DB 접속 정보
  datasource:
    url: jdbc:mysql://${db.host}:${db.port}/${db.name}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${db.user}
    password: ${db.pass}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect


  # 파일 업로드 용량 제한
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  # 코드 변경 시 자동 재시작 기능
  devtools:
    restart:
      enabled: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.trading.dto

server:
  port: 8081

# 전체 로그 기본 설정
logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.springframework.web: info

# Swagger 설정
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none