spring:
  application:
    name: coin-auto-trading

  profiles:
    active: secret

  #DB 접속 정보
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect


  # 파일 업로드 용량 제한
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  # 코드 변경 시 자동 재시작 기능
  devtools:
    restart:
      enabled: true

server:
  port: 8081

# 전체 로그 기본 설정
logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.springframework.web: info